#!/bin/bash

usage() {
	echo "
	to apply a scheme:
		makexuse a|apply <colorname>

	to list all available schemes:
		makexuse l|list

	update links to colours
		makexuse r|relink
	"
}

listcolours() {
	exa -G $HOME/.termcolors
}

relinkcolours() {
	{
		cp -sf $HOME/.GitDots/crayolo/colors/* $HOME/.termcolors/.
		cp -sf $HOME/.GitDots/ib250/* $HOME/.termcolors/.
	} 2> /dev/null
}

togglebar() {
  pgrep polybar && {
    pkill polybar
    polybar example
  } > /dev/null
}

showcolours() {
  case ${requested} in
    *.png ) colors -n 18 ${1} ;;
    * ) cat ${1} | awk '{print $NF}' | grep "#" ;;
  esac | hex2col
}

usethisone() {
	source $HOME/.bash_aliases

	# where are they?
	dir=$HOME/.termcolors

	# remove the old one
	[ -e "${dir}/xuse" ] && rm ${dir}/xuse

	# copy target
	cat "$1" > ${dir}/xuse

	# transparancy
	sed -e "s/define /define a/g; s/ #/ #D9/g;" $1 >> ${dir}/xuse

	# reload Xresources
	xrdb $HOME/.Xresources
	export barBG=$(xrdb -query | grep "*background" | awk '{print $NF}')
	export barFG=$(xrdb -query | grep "*foreground" | awk '{print $NF}')

	# chang bsp stuff
	bspc config normal_border_color ${barBG}
	bspc config focused_border_color ${barFG}
	bspc config active_border_color ${barFG}
	bspc config presel_feedback_color ${barFG}

	# update zathurarc and vimb
  use_xuse.py

  # blend
  blend &
}

# default options
nowall=false
nobar=false

for i in "$@"
do
	case "$i" in
		*nobar* ) nobar=true; echo "NO BAR";;
		*nowall* ) nowall=true; echo "NO WALL";;
	esac
done


# begin
case ${1} in
	l|list ) listcolours ;;
	r|relink ) echo "
    Relinking colours
    " && relinkcolours ;;
	a|apply )
    # colours
    f=$HOME/.termcolors/${2}
		usethisone ${f}
    # bar
		${nobar} || togglebar &
    # wall
		${nowall} || {
      blend ${blend_options} &
		}; showcolours ${f}
    ;;
	* ) usage ;;
esac
