#!/usr/bin/env sh

termiteconfig() {

    COLORS=$(xrdb -query | ag "color(\d+)" | sed -e s/\*color/color/g -e s/\*\.color/color/g -e s/\:/\=/g)
    which termite && {
        TERMITE_CONFIG=${HOME}/.config/termite/config

        [ -e ${TERMITE_CONFIG} ] && rm ${TERMITE_CONFIG}
        echo "
[options]
font = Fira Code 12
scrollback_lines = -1
hyperlinks = true

[hints]
font = Fira Code 12
padding = 2
roundness = 2.0

[colors]
${COLORS}
        " > ${TERMITE_CONFIG}
    }
}

zathuraconfig() {
	which zathura && {
	    # update zathurarc
	    ZRC=${HOME}/.config/zathura/zathurarc 

	    [ -e ${ZRC} ] && rm ${ZRC}
	    echo "
		# Open document in fit-width mode by default
		set adjust-open \"width\"
		# One page per row by default
		set pages-per-row 1
		set recolor-reverse-video True
		set recolor-keephue
		set recolor

		# Appearance
		set default-bg \""${barBG}"\"
		set default-fg \""${barFG}"\"
		set inputbar-bg \""${barBG}"\"
		set inputbar-fg \""${barFG}"\"
		set statusbar-bg \""${barBG}"\"
		set statusbar-fg \""${barFG}"\"
		set recolor-lightcolor \""${barBG}"\"
		set recolor-darkcolor \""${barFG}"\"
		set highlight-color \""${barFG}"\"
		set highlight-active-color \""${barBG}"\"
		set completion-bg \""${barBG}"\"
		set completion-fg \""${barFG}"\"
		set completion-group-fg \""${barFG}"\"
		set completion-group-bg \""${barBG}"\"
		set completion-highlight-bg \""${barFG}"\"
		set completion-highlight-fg \""${barBG}"\"
		set index-bg \""${barBG}"\"
		set index-fg \""${barFG}"\"
		set index-active-bg \""${barFG}"\"
		set index-active-fg \""${barBG}"\"
		" > ${HOME}/.config/zathura/zathurarc
	}
}

config() {

	# remove the old one
	[ -e "xuse" ] && rm xuse

	# copy target
	[ -e "${1}" ] && {
	    cat "$1" > xuse
	}

	# change stuff to add transparency
	sed -e "s/define /define a/g; s/ #/ #D9/g;" $1 >> xuse
	echo "#define xftfnt xft:Fira Mono:style=regular:size=11" >> xuse
	echo "#define fnt Fira Mono Regular 11" >> xuse
    zathuraconfig
}

apply() {

	# reload Xresources
	which xrdb && xrdb $HOME/.Xresources || {
	    echo "xrdb command not found, skipping..."
	}

	export barBG=$(xrdb -query | \
	    grep "*background" | \
	    awk '{print $NF}')

	export barFG=$(xrdb -query | \
	    grep "*foreground" | \
	    awk '{print $NF}')

	# reset wall
	which hsetroot && hsetroot -solid "${barBG}" || {
	    echo "hsetroot command not found, skippint..."
	}

    termiteconfig

	# chang bsp stuff
	pgrep bspwm && {

	    bspc config normal_border_color "${barBG}"
	    bspc config focused_border_color "${barFG}"
	    bspc config active_border_color "${barFG}"
        polybar --reload main

	}

}

case ${1} in
	apply ) shift && apply $*;;
	config ) shift && config $*;;
    use )
        shift
        config $*
        apply $*
        ;;
	* ) echo "<script> [config|apply] <file>";;
esac
