#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#

[ -e "${HOME}/.bash_aliases" ] && . ${HOME}/.bash_aliases

# enable stack autocompletion if i have stack setup
# slow on pretzo in WSL :(
# [ -e "$(which stack)" ] && {
#   autoload -U +X compinit && compinit
#   autoload -U +X bashcompinit && bashcompinit
#   eval "$(stack --bash-completion-script stack)"
# }

bindkey jk vi-cmd-mode
bindkey kj vi-cmd-mode
