#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

alias c="clear"

which exa > /dev/null && {
  alias l="exa --long --all --git"
  alias ls="exa"
  alias ll="exa --long --git"
  alias trls="exa -T -L 1"
  alias tree="exa -T"
} || {
  alias l="ls -lah"
  alias ll="ls -l"
}

which lataxmk > /dev/null && {
  alias quickLuaTex="latexmk -lualatex"
  alias quickPdfTex="latexmk -pdf"
}

alias q="exit" 

which pacman > /dev/null && {
  alias nix='. /home/ismail/.nix-profile/etc/profile.d/nix.sh'
}

# Customize to your needs...
bindkey jk vi-cmd-mode
bindkey kj vi-cmd-mode
